# Generated by Django 3.0.3 on 2020-06-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='scanned_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
