# Generated by Django 3.0.3 on 2020-06-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_auto_20200610_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='available',
            new_name='mark',
        ),
        migrations.RemoveField(
            model_name='result',
            name='obtained',
        ),
    ]
